name: Construction et publication de Docker Image sur le registre GitHub Packages

on:
  push:
    branches:
      - main
     
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      actions: write
      id-token: write

    steps:
      # Télécharge le contenu du repository sur l'agent d'exécution.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 

      # Connexion au Registre Docker
      - name: Log into registry 
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 
        with:
          context: .
          push: True
          tags: ghcr.io/alexandermosiej/ue19-lab-05

      
